### PR TITLE
added support for SE, BE, AT, NO, DE, LU, DK, FR

### PR DESCRIPTION
**Pull request by Mobbit**

### CODE REVIEW

**Comment by monfresh** [comment]
Hi @matsadler. I'm not sure if you're the one maintaining this gem, but I was wondering if there were any plans to merge these pull requests that have been open for a year now. Thanks!

**Comment by matsadler** [comment]
@monfresh I don't work for Global Personals anymore, so I'm no longer a collaborator on this project. Maybe @timblair or @mendable will be able to help you.

**Comment by timblair** [comment]
Just seen this. Sorry for the delay, @monfresh! I'll have a look through things over the next few days.

**Comment by timblair** [comment]
OK, finally got around to looking over things. Looks good :+1: Thanks for the contribution, @Mobbit, and my apologies again for the delay.

**Comment by timblair** [comment]
`0.1.6` (which includes this change) is now available on rubygems.org.

**Pull request merged**
